import type { DemoOrder } from "./types";

export const DEMO_ORDER: DemoOrder = {
  orderNumber: "#1003",
  customerName: "Max Mustermann",
  platform: "Shopify",
  shop: "Shopify-Shop",
  country: "DE",
  amount: "6324.65 EUR",
  items: [
    {
      id: "item-1",
      title: "The Complete Snowboard Dawn",
      sku: "BILLBEE-500000000644354",
      quantity: 1,
      scannedQuantity: 0,
      storageLocation: "16",
      imageColor: "bg-teal-200",
    },
    {
      id: "item-2",
      title: "The Complete Snowboard Dawn",
      sku: "BILLBEE-500000000644354",
      quantity: 1,
      scannedQuantity: 0,
      storageLocation: "16",
      imageColor: "bg-teal-300",
    },
    {
      id: "item-3",
      title: "The Complete Snowboard",
      sku: "BILLBEE-500000000644352",
      quantity: 1,
      scannedQuantity: 0,
      storageLocation: "15",
      imageColor: "bg-emerald-300",
    },
    {
      id: "item-4",
      title: "The Complete Snowboard Electric",
      sku: "BILLBEE-500000000644356",
      quantity: 1,
      scannedQuantity: 0,
      storageLocation: "18",
      imageColor: "bg-teal-400",
    },
    {
      id: "item-5",
      title: "The Complete Snowboard Ice",
      sku: "BILLBEE-500000000644353",
      quantity: 1,
      scannedQuantity: 0,
      storageLocation: "17",
      imageColor: "bg-cyan-200",
    },
    {
      id: "item-6",
      title: "Bundle_test",
      sku: "Set-1",
      quantity: 1,
      scannedQuantity: 0,
      storageLocation: "",
      imageColor: "bg-gray-300",
    },
    {
      id: "item-7",
      title: "Gift Card",
      sku: "BILLBEE-500000000644338",
      quantity: 1,
      scannedQuantity: 0,
      storageLocation: "4",
      imageColor: "bg-rose-300",
    },
    {
      id: "item-8",
      title: "Gift Card $10",
      sku: "BILLBEE-500000000644339",
      quantity: 1,
      scannedQuantity: 0,
      storageLocation: "5",
      imageColor: "bg-rose-400",
    },
  ],
};
